### ISSUE TITLE
Data Validation for User input to Algorithms and Data structures

### ISSUE THREAD

**Issue by BavlyRemon** [AUC-SWE-Team-SCRUMptious/DSA_Visualizer#9]
Receive the data given by the user and validate it to check if it adheres to the rules mentioned in the SRS 1.3
If the data is invalid, an error message is displayed under the text box.

**Comment by OmarElfouly** [comment]
Inputs:
userInput: String, DSAName: String

Output:
valid: Bool, msg: String, data: ArrayOfInts
